services:
  db:
    build: 
      context: ./MySQL
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
  wordpress:
    depends_on:
      - db
    build:
      context: ./Wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 8080:80
    expose:
      - 80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
volumes:
  db_data: {}
  wordpress_data: {}